name: talon
description: "Talon™ POS — Strike fast. Track everything."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Dependency injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Routing
  go_router: ^15.1.2

  # Models & serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Local database
  drift: ^2.25.0
  sqlite3_flutter_libs: ^0.5.30
  path_provider: ^2.1.5
  path: ^1.9.1

  # Fonts & UI
  google_fonts: ^6.2.1

  # Security
  flutter_secure_storage: ^9.2.4

  # Network
  connectivity_plus: ^6.1.4

  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  supabase_flutter: ^2.12.0
  file_picker: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.9.5
  injectable_generator: ^2.7.0
  drift_dev: ^2.25.0

  # Testing
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
